name: Warden
description: Helps stop more exploits, and cheats than any other anti-cheat.
authors: [LordLambda]
main: io.ll.warden.Warden
version: 1.0-SNAPSHOT
depend: [ProtocolLib]
startup: postworld

commands:
  verify:
    description: Verifies certain actions for warden
    usage: /verify <action> <password>
  registerWarden:
    description: Register A Warden Account
    usage: /rW <user> <pass> <rank>
    aliases: rW
  loginWarden:
    description: Login to a warden account
    usage: /login <pass>
    aliases: login
  promoteWarden:
    description: Promote someones warden account
    usage: /pW <user> <level>
    aliases: pW
  pardonWarden:
    description: Unbans someone who was banned by warden.
    usage: /pardW <user>
    aliases: pardW